spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_exam?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 938765
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 排除 BeetlSQL 自动的配置
  autoconfigure:
    exclude: com.ibeetl.starter.BeetlSqlSingleConfig


mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  config-location: classpath:/mapper/mybatis-config.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.chachae.exam.common.model
  global-config:
    banner: false
    db-config:
      # 表驼峰下划线转换
      table-underline: true
      # id 自增
      id-type: auto

#beetl:
#  enabled: true
#  suffix: btl
#beetl-beetlsql:
#  dev: true